spring:
  application:
    name: application money control
  main:
    banner-mode: off
  datasource:
    url: jdbc:h2:mem:mydb
    username: username
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect